on:
    push:
        branches:
            - main
    pull_request:

name: Tests

jobs:
    tests:
        name: Unit tests (Node ${{ matrix.node-version }})
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18, 19, 20]
            fail-fast: false
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm test
